# Generated by Django 4.1.6 on 2023-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('otp_secret_key', models.CharField(max_length=16)),
            ],
        ),
    ]
