# Generated by Django 4.1.6 on 2023-04-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnnit', '0002_remove_user_otp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
